#!/usr/bin/php
<?php

/*
 *  CONFIG VARS
 */
$versionFile		= 'VERSION';
$changesFile		= 'CHANGES';
$tempChangesFile	= 'TMP_CHANGES';
//$editor			= '/usr/bin/vim';
$editor				= 'C:\Program^ Files\Notepad++\notepad++.exe';
$changesPrefix		= '* ';
$initialVersion		= '0.0.0';
$versionTagPrefix	= 'v';

/*
 * MAIN PROGRAM
 */
if( !file_exists( $versionFile ) )
{
	file_put_contents( $versionFile, $initialVersion );
}

$lastVersion		= file_get_contents( $versionFile );
printf( "Current version : %s\n", $lastVersion );
list( $versionMajor, $versionMinor, $versionPatch )	= explode('.', $lastVersion);

// Set New Version
$versionMinor++;
$versionPatch		= 0;
$suggestedVersion	= sprintf( "%d.%d.%d", $versionMajor, $versionMinor, $versionPatch );
printf( "Enter a version number [%s]: ", $suggestedVersion );
$input				= trim( fgets( STDIN ) );
if( ! empty( $input ) )
	$suggestedVersion	= $input;

// Fetch CHANGES , edit its and append to CHAGES file
$gitLogCommand		= ( $lastVersion === $initialVersion )
					? sprintf( 'git log --pretty=format:" %s%%s"', $changesPrefix )
					: sprintf( 'git log --pretty=format:" %s%%s"  %s%s...HEAD', $changesPrefix, $versionTagPrefix, $lastVersion );

$changes			= sprintf(
	"%s:\n-----\nRelease date: **%s**\n\n%s\n\n",
	$suggestedVersion,
	date( "d.m.Y" ),
	shell_exec( $gitLogCommand )
);
file_put_contents( $tempChangesFile, $changes );
exec( "$editor $tempChangesFile" );
$oldChanges			= file_exists( $changesFile ) ? file_get_contents( $changesFile ) : '';
file_put_contents( $tempChangesFile, $oldChanges, FILE_APPEND );
rename( $tempChangesFile, $changesFile );

file_put_contents( $versionFile, $suggestedVersion );

// Commit VERSION and CHANGES files
exec( sprintf( 'git add %s %s', basename( $versionFile ), basename( $changesFile ) ) );
exec( sprintf( 'git commit -m "Version bump to %s"', $suggestedVersion ) );
